/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    screens: {
      sm: '480px',
      md: '768px',
      lg: '1120px',
      xl: '1440px',
      '2xl': '1980px'
    },
    fontSize: {
      sm: '0.75rem',
      'sm-mobile': '0.875rem',
      'sm-title': '0.875rem',
      'sm-mobile-tab': '0.625rem',
      'chat-header-title': '1rem',
      'actions-popover-menu-item': '15px',
      'setting-title': '1.25rem',
      'setting-items': '1rem',
    },
    fontFamily: {
      'common': ['Satoshi Variable', "SF Pro Text", "SF Pro Icons", "Helvetica Neue", 'Helvetica', 'Arial', 'sans-serif'],
      'time': ['Hind', "SF Pro Text", "SF Pro Icons", "Helvetica Neue", 'Helvetica', 'Arial', 'sans-serif'],
      'setting-card-title': ['PingFang HK', 'PingFang', "SF Pro Text", "SF Pro Icons", "Helvetica Neue", 'Helvetica', 'Arial', 'sans-serif']
    },
    extend: {
      lineHeight: {
        'slide-btn': "17px",
        'input': '22px',
      },
      backdropBlur: {
        'chat-header': '20px',
      },
      minHeight: {
        'chat-input-mobile': '19px',
        'chat-input': '60px',
      },
      height: {
        mobile: 'var(--siderbar-mobile-height)',
        // mobile: '3.125rem',
        'menu-title-mobile': '3rem',
        'thumbnail': '5rem',
        'chat-input-mobile': '19px',
        'chat-input': '60px',
        'chat-panel-mobile': '- var(--siderbar-mobile-height)',
        'setting-panel-mobile': 'calc(100vh - var(--siderbar-mobile-height))',
        'slide-btn': '18px',
        'switch': '1rem',
        'chat-header-title-mobile': '19px',
        'model-bottom-drawer': 'calc(100vh - 110px)',
      },
      minWidth: {
        'select-mobile-lg': '200px',
        'select-mobile': '170px',
        'select': '240px',
        'slide-range-mobile-lg': '200px',
        'slide-range-mobile': '170px',
        'slide-range': '240px',
      },
      width: {
        'md': '15rem',
        'lg': '21.25rem',
        '2xl': '27.5rem',
        'page': 'calc(100% - var(--menu-width))',
        'thumbnail': '5rem',
        'actions-popover': '203px',
        'switch': '2rem',
        'modal-modal-type': '26.25rem',
        'modal-modal-type-mobile': 'calc(100vw - 2 * 44px)',
      },
      flexBasis: {
        'sidebar': 'var(--menu-width)',
        'page': 'calc(100% - var(--menu-width))',
        'message-width': 'var(--max-message-width)',
      },
      spacing: {
        'chat-header-gap': '0.625rem',
        'chat-panel-mobile': 'var(--siderbar-mobile-height)',
        'message-img': 'calc((100%- var(--img-gap-count)*0.25rem)/var(--img-count))',
      },
      backgroundColor: {
        'global': 'var(--global-bg)',
        'global-mobile': 'var(--global-mobile-bg)',
        'actions-bar-btn-default': 'var(--actions-bar-btn-default-bg)',
        'primary-btn': 'var(--primary-btn-bg)',
        'primary-btn-disabled': 'var(--primary-btn-disabled-bg)',
        'danger-btn': 'var(--danger-btn-bg)',
        'default-btn': 'var(--default-btn-bg)',
        'hovered-btn': 'var(--hovered-btn-bg)',
        'hovered-danger-btn': 'var(--hovered-danger-btn-bg)',
        'card': 'var(--card-bg)',
        'input': 'var(--input-bg)',
        'list-item-divider': 'var(--list-item-divider-bg)',
        'menu': 'var(--menu-bg)',
        'select-option-hovered': 'var(--select-option-hovered-bg)',
        'select-popover-panel': 'var(--select-popover-panel-bg)',
        'select': 'var(--select-bg)',
        'slider': 'var(--slider-bg)',
        'slider-slided-travel': 'var(--slider-slided-travel-bg)',
        'slider-block': 'var(--slider-block-bg)',
        'slider-block-hover': 'var(--slider-block-hover-bg)',
        'switch-unchecked': 'var(--switch-unchecked-bg)',
        'switch-checked': 'var(--switch-checked-bg)',
        'switch-btn': 'var(--switch-btn-bg)',
        'chat-actions-popover-panel-mobile': 'var(--chat-actions-popover-panel-mobile-bg)',
        'chat-actions-btn-popover': 'var(--chat-actions-btn-popover-bg)',
        'chat-actions-btn-hovered': 'var(--chat-actions-btn-hovered-bg)',
        'chat-panel-header-mask': 'var(--chat-panel-header-mask-bg)',
        'chat-panel-header-mobile': 'var(--chat-panel-header-mobile-bg)',
        'chat-panel-input-hood': 'var(--chat-panel-input-hood-bg)',
        'chat-panel-message-user': 'var(--chat-panel-message-user-bg)',
        'chat-panel-message-bot': 'var(--chat-panel-message-bot-bg)',
        'chat-panel-message': 'var(--chat-panel-message-bg)',
        'chat-panel-message-mobile': 'var(--chat-panel-message-mobile-bg)',
        'chat-message-actions': 'var(--chat-message-actions-bg)',
        'chat-message-actions-btn-hovered': 'var(--chat-message-actions-btn-hovered-bg)',
        'chat-panel': 'var(--chat-panel-bg)',
        'chat-panel-message-clear-divider': 'var(--chat-panel-message-clear-divider-bg)',
        'chat-menu-session-selected': 'var(--chat-menu-session-selected-bg)',
        'chat-menu-session-selected-mobile': 'var(--chat-menu-session-selected-mobile-bg)',
        'chat-menu-session-unselected': 'var(--chat-menu-session-unselected-bg)',
        'chat-menu-session-unselected-mobile': 'var(--chat-menu-session-unselected-mobile-bg)',
        'chat-menu-session-hovered': 'var(--chat-menu-session-hovered-bg)',
        'settings-menu-mobile': 'var(--settings-menu-mobile-bg)',
        'settings-menu-item-mobile': 'var(--settings-menu-item-mobile-bg)',
        'settings-menu-item-selected': 'var(--settings-menu-item-selected-bg)',
        'settings-header-mobile': 'var(--settings-header-mobile-bg)',
        'settings-panel': 'var(--settings-panel-bg)',
        'sidebar-mobile': 'var(--sidebar-mobile-bg)',
        'sidebar-btn-hovered': 'var(--sidebar-btn-hovered-bg)',
        'delete-chat-popover-panel': 'var(--delete-chat-popover-panel-bg)',
        'modal-mask': 'var(--modal-mask-bg)',
        'moda-panel': 'var(--modal-panel-bg)',
        'delete-chat-ok-btn': 'var(--delete-chat-ok-btn-bg)',
        'delete-chat-cancel-btn': 'var(--delete-chat-cancel-btn-bg)',
        'menu-dragger': 'var(--menu-dragger-bg)',
        'chat-actions-select-model': 'var(--chat-actions-select-model-bg)',
        'chat-actions-select-model-hover': 'var(--chat-actions-select-model-hover-bg)',
        'select-hover': 'var(--select-hover-bg)',
        'input-input-ele-hover': 'var(--input-input-ele-hover-bg)',
        'model-select-popover-panel': 'var(--model-select-popover-panel-bg)',
      },
      backgroundImage: {
        // 'chat-panel-message-user': 'linear-gradient(259deg, #9786FF 8.42%, #4A5CFF 90.13%)',
        'thumbnail-mask': 'linear-gradient(0deg, rgba(0, 0, 0, 0.50) 0%, rgba(0, 0, 0, 0.50) 100%)',
      },
      transitionProperty: {
        'time': 'all ease 0.6s',
        'message': 'all ease 0.3s',
      },
      maxHeight: {
        'chat-actions-select-model-popover': '340px',
      },
      maxWidth: {
        'message-width': 'var(--max-message-width)',
        'chat-actions-select-model': '282px',
      },
      boxShadow: {
        'btn': 'var(--btn-shadow)',
        'chat-actions-popover-mobile': 'var(--chat-actions-popover-mobile-shadow)',
        'chat-input-hood-focus-shadow': 'var(--chat-input-hood-focus-shadow)',
        'select-popover-shadow': 'var(--select-popover-shadow)',
        'message-actions-bar': 'var(--message-actions-bar-shadow)',
        'prompt-hint-container': 'var(--prompt-hint-container-shadow)',
        'delete-chat-popover-shadow': 'var(--delete-chat-popover-shadow)',
        'sidebar-btn-shadow': 'var(--sidebar-btn-shadow)',
      },
      colors: {
        'select-popover': 'var(--select-popover-border)',
        'slider-block': 'var(--slider-block-border)',
        'thumbnail': 'var(--thumbnail-border)',
        'chat-actions-popover-mobile': 'var(--chat-actions-popover-mobile-border)',
        'chat-header-bottom': 'var(--chat-header-bottom-border)',
        'chat-input-top': 'var(--chat-input-top-border)',
        'chat-input-hood': 'var(--chat-input-hood-border)',
        'chat-input-hood-focus': 'var(--chat-input-hood-focus-border)',
        'settings-menu-item-selected': 'var(--settings-menu-item-selected-border)',
        'settings-header': 'var(--settings-header-border)',
        'delete-chat-popover': 'var(--delete-chat-popover-border)',
        'delete-chat-cancel-btn': 'var(--delete-chat-cancel-btn-border)',
        'chat-menu-session-selected': 'var(--chat-menu-session-selected-border)',
        'chat-menu-session-selected-mobile': 'var(--chat-menu-session-selected-mobile-border)',
        'chat-menu-session-unselected': 'var(--chat-menu-session-unselected-border)',
        'chat-menu-session-unselected-mobile': 'var(--chat-menu-session-unselected-mobile-border)',
        'chat-menu-session-hovered': 'var(--chat-menu-session-hovered-border)',
        'modal-header-bottom': 'var(--modal-header-bottom-border)',
        'transparent': 'transparent',

        'text-sidebar-tab-mobile-active': 'var(--sidebar-tab-mobile-active-text)',
        'text-sidebar-tab-mobile-inactive': 'var(--sidebar-tab-mobile-inactive-text)',
        'text-btn-primary': 'var(--btn-primary-text)',
        'text-btn-danger': 'var(--btn-danger-text)',
        'text-btn-default': 'var(--btn-default-text)',
        'text-card-title': 'var(--card-title-text)',
        'text-input': 'var(--input-text)',
        'text-select': 'var(--select-text)',
        'text-select-option': 'var(--select-option-text)',
        'text-modal-select': 'var(--modal-select-text)',
        'text-list-title': 'var(--list-title-text)',
        'text-list-subtitle': 'var(--list-subtitle-text)',
        'text-slider-block': 'var(--slider-block-text)',
        'text-chat-actions-btn-popover': 'var(--chat-actions-btn-popover-text)',
        'text-chat-header-title': 'var(--chat-header-title-text)',
        'text-chat-header-subtitle': 'var(--chat-header-subtitle-text)',
        'text-chat-input-placeholder': 'var(--chat-input-placeholder-text)',
        'text-chat-message-date': 'var(--chat-message-date-text)',
        'text-chat-message-markdown-user': 'var(--chat-message-markdown-user-text)',
        'text-chat-message-markdown-bot': 'var(--chat-message-markdown-bot-text)',
        'text-chat-panel-message-clear': 'var(--chat-panel-message-clear-text)',
        'text-chat-panel-message-clear-revert': 'var(--chat-panel-message-clear-revert-text)',
        'text-chat-menu-item-title': 'var(--chat-menu-item-title-text)',
        'text-chat-menu-item-time': 'var(--chat-menu-item-time-text)',
        'text-chat-menu-item-delete': 'var(--chat-menu-item-delete-text)',
        'text-chat-menu-item-description': 'var(--chat-menu-item-description-text)',
        'text-settings-menu-title': 'var(--settings-menu-title-text)',
        'text-settings-menu-item-title': 'var(--settings-menu-item-title-text)',
        'text-settings-panel-header-title': 'var(--settings-panel-header-title-text)',
        'text-modal-panel': 'var(--modal-panel-text)',
        'text-delete-chat-ok-btn': 'var(--delete-chat-ok-btn-text)',
        'text-delete-chat-cancel-btn': 'var(--delete-chat-cancel-btn-text)',
        'text-primary-btn-disabled-dark': 'var(--primary-btn-disabled-dark-text)',
        'text-modal-title': 'var(--modal-title-text)',
        'text-modal-content': 'var(--modal-content-text)',
      },
      keyframes: {
        mask: {
          '0%': { opacity: 0 },
          '100%': { opacity: 1 },
        }
      },
      animation: {
        mask: 'mask 150ms cubic-bezier(0.16, 1, 0.3, 1)'
      }
    },
    borderRadius: {
      'none': '0',
      'sm': '0.125rem',
      DEFAULT: '0.25rem',
      'md': '0.75rem',
      'lg': '1rem',
      'user-message': '16px 4px 16px 16px',
      'bot-message': '4px 16px 16px 16px',
      'action-btn': '0.5rem',
      'actions-bar-btn': '0.375rem',
      'chat-input': '0.5rem',
      'chat-img': '0.5rem',
      'slide': '0.625rem',
      'chat-model-select': '1.25rem',
    },
    borderWidth: {
      DEFAULT: '1px',
    },
  },
  plugins: [],
}

