apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-earth
spec:
  displayName: Earth
  author:
    name: halo-dev
    website: https://halo.run
  description: Default theme for Halo 2.0
  logo: https://halo.run/logo
  website: https://github.com/halo-dev/theme-earth
  repo: https://github.com/halo-dev/theme-earth.git
  settingName: "theme-earth-setting"
  configMapName: "theme-earth-configMap"
  version: 1.2.1
  require: ">=2.1.0"
