
OPENAI_API_TYPE="OPENAI_API_TYPE"
OPENAI_DEPLOYMENT_NAME="OPENAI_DEPLOYMENT_NAME"
OPENAI_MODEL="OPENAI_MODEL"
OPENAI_API_VERSION="OPENAI_API_VERSION"
OPENAI_API_BASE="OPENAI_API_BASE"
OPENAI_API_KEY="OPENAI_API_KEY"

